services:
  - docker

script:
- echo "hello world"
- docker build --target test --tag my-test-image .
- docker run my-test-image todo_app/items_test.py    
- docker run my-test-image todo_app/integration_test.py  
- docker run -e TOKEN -e KEY -e TOID -e DOINGID -e DONE my-test-image  todo_app/e2e_test.py 

script:
-docker build --target production --tag my-production-image .

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build --target production --tag $DOCKER_USERNAME/my-production-image:TRAVIS_COMMIT .
- docker push $DOCKER_USERNAME/my-production-image:TRAVIS_COMMIT 

